development: &main_settings
  app_name: kabupatenku
  basic_auth_name: username
  basic_auth_password: password
  host: localhost:3000   # defaults to localhost:3000 otherwise
  
  # use the following settings with mailcatcher; only used in development
  delivery_method: smtp
  smtp_settings:
    host: localhost
    port: 1025
  # use the following settings for local sendmail; only used in development
  delivery_method: sendmail
